name: Mirror Linux TPM Tree

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH deploy key
        env:
          SSH_KEY: ${{ secrets.TPM_MIRROR_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Mirror Linux TPM tree
        run: |
          set -eux

          git clone --mirror \
            https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-tpmdd.git \
            linux-tpmdd.git

          cd linux-tpmdd.git

          git remote set-url --push origin \
            git@github.com:r1chard-lyu/linux-tpmdd-mirror.git

          git push --mirror