name: Mirror Linux EFI Tree

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH deploy key
        env:
          SSH_KEY: ${{ secrets.EFI_MIRROR_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Mirror Linux EFI tree
        run: |
          set -eux

          git clone --mirror \
            https://kernel.googlesource.com/pub/scm/linux/kernel/git/efi/efi.git \
            efi.git

          cd efi.git

          git remote set-url --push origin \
            git@github.com:r1chard-lyu/linux-efi-mirror.git

          git push --mirror